0chnxxx/Algorithm-Challenge

goorm/0chnxxx/난이도2_구름_찾기_깃발.kt

- https://level.goorm.io/exam/195689/%EA%B5%AC%EB%A6%84-%EC%B0%BE%EA%B8%B0-%EA%B9%83%EB%B0%9C/quiz/1
- 프로그래밍
- 
-

[난이도2] 구름 찾기 깃발

---

goorm/0chnxxx/난이도2_문자열_나누기_2.kt

- https://level.goorm.io/exam/195688/%EB%AC%B8%EC%9E%90%EC%97%B4-%EB%82%98%EB%88%84%EA%B8%B0/quiz/1
- 프로그래밍
- 
-

[난이도2] 문자열 나누기 2

---

goorm/0chnxxx/난이도2_거울_단어.kt

- https://level.goorm.io/exam/49066/%EA%B1%B0%EC%9A%B8-%EB%8B%A8%EC%96%B4/quiz/1
- 프로그래밍
- 
- 테스트 케이스 7번이 왜 자꾸 실패하는걸까..
- 7번은 성공시켜놓고 10번을 실패
- "거울 단어"라는 정의가 문제 설명에서 부족했던 느낌

[난이도2] 거울 단어

---

goorm/0chnxxx/난이도1_인공지능_청소기.kt

[GRM] 난이도1 / 인공지능 청소기 / 13분

---

baekjoon/0chnxxx/다리를_지나는_트럭.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42583
- 스택/큐
- 프로그래머스는 import를 직접 넣어줘야한다.
-

[BOJ] 난이도2 / 다리를 지나는 트럭 / 86분

---

goorm/0chnxxx/수열.kt

- https://level.goorm.io/exam/175018/%ED%94%BC%EB%B3%B4%EB%82%98%EC%B9%98-%EC%88%98/quiz/1
- DP
- 
-

[GRM] 난이도2 / 수열 / 6분

---

goorm/0chnxxx/난이도3_불이야!!.kt

- https://level.goorm.io/exam/49051/%EB%B6%88%EC%9D%B4%EC%95%BC/quiz/1
- 자료구조
- 아 BFS 어렵다...
- 뭔가 퍼져가는? 번져가는? 듯한 작업을 해야될 때 Queue에 담아두고 다 빌 때까지 반복
- 이 때 작업에서 우선순위가 필요하다면 PriorityQueue를 사용
- 작업의 상태를 저장하고 후처리가 필요하다면 visited 배열을 잘 활용
-

[GRM] 난이도3 / 불이야!! / 56분

---

goorm/0chnxxx/개미_집합의_지름.kt

- https://level.goorm.io/exam/49060/%EA%B0%9C%EB%AF%B8-%EC%A7%91%ED%95%A9%EC%9D%98-%EC%A7%80%EB%A6%84/quiz/1
- 탐색
- https://0chnxxx.oopy.io/118c9413-0950-8047-9ce5-c499bf260a21
- 투 포인터라는 탐색 알고리즘을 배웠습니다.
-

[GRM] 난이도2 / 개미 집합의 지름 / 12분

---

goorm/0chnxxx/난이도3_ADAS_시스템.kt

- https://level.goorm.io/exam/152116/%ED%98%84%EB%8C%80%EB%AA%A8%EB%B9%84%EC%8A%A4-%EC%98%88%EC%84%A0-adas-%EC%8B%9C%EC%8A%A4%ED%85%9C/quiz/1
- 자료구조
- 로직대로 구현은 할 수 있지만 효율성을 챙기려면 BFS 같은 기법을 사용해야했다..
- BFS를 사용했음에도 11번, 17번 케이스가 자꾸 타임아웃이 발생했다.
- BFS에서 visited를 관리하는 배열을 boolean 타입으로 바꿔서 개선했더니 해결됐다.
-

[GRM] 난이도3 / ADAS 시스템 / 118분

---

goorm/0chnxxx/난이도3_거리두기.kt

- https://level.goorm.io/exam/160279/%EA%B1%B0%EB%A6%AC%EB%91%90%EA%B8%B0/quiz/1
- DP
- 그냥 어렵다..
-

[GRM] 난이도3 / 거리두기 / 51분

---

goorm/0chnxxx/난이도3_단풍나무.kt

- https://level.goorm.io/exam/167345/%EB%8B%A8%ED%92%8D%EB%82%98%EB%AC%B4/quiz/1
- 구현
- 메서드를 잘 나누는게 나도 보기 편하다.
-

[GRM] 난이도3 / 단풍나무 / 31분

---

goorm/0chnxxx/정수의_길이.kt

- https://level.goorm.io/exam/173089/%EC%A0%95%EC%88%98%EC%9D%98-%EA%B8%B8%EC%9D%B4/quiz/1
- 프로그래밍
- 
-

[GRM] 난이도1 / 정수의 길이 / 1분

---

goorm/0chnxxx/거스름돈.kt

- https://level.goorm.io/exam/175177/%EA%B1%B0%EC%8A%A4%EB%A6%84-%EB%8F%88/quiz/1
- 그리디
- 
-

[GRM] 난이도2 / 거스름돈 / 5분

---

goorm/0chnxxx/구름스퀘어.kt

- https://level.goorm.io/exam/175194/%EA%B5%AC%EB%A6%84-%EC%8A%A4%ED%80%98%EC%96%B4/quiz/1
- 그리디
- https://airy-trampoline-a11.notion.site/11bc9413095080daac83d10ba35b0438
- 그리디가 무엇인지 공부했습니다.
-

[GRM] 난이도2 / 구름스퀘어 / 32분

---

goorm/0chnxxx/난이도2_블록_게임.kt

- https://level.goorm.io/exam/191052/%EB%B8%94%EB%A1%9D-%EA%B2%8C%EC%9E%84/quiz/1
- 자료 구조
- 너무 문제 설명대로 구현을 하려는 경향이 있다.
- 2차원 배열이라길래 무작정 2차원 배열을 만들었는데 굳이 그럴 필요가 없었다.
- 히스토리를 관리하기만 하면 돼서 그냥 리스트로 했더니 간단하게 해결됐다.
-

[GRM] 난이도2 / 블록 게임 / 41분

---

goorm/0chnxxx/동전_퍼즐.kt

- https://level.goorm.io/exam/195037/%EB%8F%99%EC%A0%84-%ED%8D%BC%EC%A6%90/quiz/1
- 탐색 (브루트포스)
- 무작정 모든 경우의 수를 다 찍어봐도 되는구나!
-

[GRM] 난이도2 / 동전 퍼즐 / 62분

---

goorm/0chnxxx/난이도2_어려운_문제.kt

- https://level.goorm.io/exam/49054/%EC%96%B4%EB%A0%A4%EC%9A%B4-%EB%AC%B8%EC%A0%9C/quiz/1
- 구현
- 숫자가 좀 커진다 싶으면 BigInteger, BigDecimal을 사용하자.
- BigInteger는 정수만, BigDecimal은 부동소수점도 다룬다.
- 왜 굳이 이렇게 큰 숫자를 계산하는걸까?..

[GRM] 난이도2 / 어려운 문제 / 16분

---

goorm/0chnxxx/난이도2_계수기_만들기.kt

- https://level.goorm.io/exam/43061/%EA%B3%84%EC%88%98%EA%B8%B0-%EB%A7%8C%EB%93%A4%EA%B8%B0/quiz/1
- 구현
- 
-

[GRM] 난이도2 / 계수기 만들기 / 39분

---

goorm/0chnxxx/난이도1_딱지놀이.kt

- https://level.goorm.io/exam/48130/%EB%94%B1%EC%A7%80%EB%86%80%EC%9D%B4/quiz/1
- 구현
- 
-

[GRM] 난이도1 / 딱지놀이 / 25분

---

goorm/0chnxxx/난이도1_소금물의_농도_구하기.kt

- https://level.goorm.io/exam/194193/%EC%86%8C%EA%B8%88%EB%AC%BC%EC%9D%98-%EB%86%8D%EB%8F%84-%EA%B5%AC%ED%95%98%EA%B8%B0/quiz/1
- 구현
- 
-

[GRM] 난이도1 / 소금물의 농도 구하기 / 23분

---

baekjoon/pjkfckr/쿼드트리.py

- https://www.acmicpc.net/problem/1992
- 재귀
- 이전에 풀었던 재귀와 형태는 비슷하나 문제를 읽었을때 괄호가 있어서 좀더 햇갈리게 풀었던것같다.
- 유형자체는 비슷한것들이 많으나, 해석에 따라 달라질수있음을 인지했다.
-

[BOJ] Silver2~3 / 쿼드트리 / 45분

---

baekjoon/0chnxxx/카펫.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42842
- 완전탐색
- 간단한 사각형 넓이 구하는 공식을 사용하는 문제
- 문제에 노란색 격자는 무조건 정사각형이라는 조건은 없는데 이런걸 어떻게 추론해야할까

[BOJ] 난이도2 / 카펫 / 39분

---

programmers/0chnxxx/연속_부분_수열_합의_개수.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/131701
- 구현
- 
-

[PGS] 난이도2 / 연속 부분 수열 합의 계수 / 28분

---

programmers/0chnxxx/할인_행사.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/131127
- 구현
- 
-

[PGS] 난이도2 / 할인 행사 / 27분

---

programmers/0chnxxx/롤케이크_자르기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/132265
- 구현
- 너무 문제에서 설명한 방식대로 구현하지 않아도 될 것 같다.
- '자른다' 라는 키워드에 사로잡혀서 배열을 슬라이싱하느라 O(n^2)의 시간복잡도가 나왔었다.
-

[PGS] 난이도2 / 롤케이크 자르기 / 14분

---

programmers/0chnxxx/뒤에_있는_큰_수_구하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/154539
- 구현
- 
-

[PGS] 난이도2 / 뒤에 있는 큰 수 찾기 / 16분

---

baekjoon/pjkfckr/스택.py

- https://www.acmicpc.net/problem/10828
- 스택
- Stack 의 개념
-

[BOJ] 난이도1 / 스택 / 10분

---

baekjoon/pjkfckr/큐.py

- https://www.acmicpc.net/problem/10845
- 큐
- 큐의 기본에 대해 알았다.
-

[BOJ] 난이도1 / 큐 / 5분

---

baekjoon/pjkfckr/덱.py

- https://www.acmicpc.net/problem/10866
- 큐
- 
-

[BOJ] 난이도1 / 큐 / 7분

---

baekjoon/pjkfckr/괄호.py

- https://www.acmicpc.net/problem/9012
- 스택
- 
-

[BOJ] 난이도 1 / 스택 / 10분

---

baekjoon/pjkfckr/좌표_압축.py

- https://www.acmicpc.net/problem/18870
- 스택, 맵
- enumerate 를 사용하여 index 와 값을 동시에 추출
-

[BOJ] 난이도 2 / Stack, Map / 20분

---

baekjoon/pjkfckr/카드2.py

- https://www.acmicpc.net/problem/2164
- 스택
- 
-

[BOJ] 난이도1 / 스택 / 7분

---

programmers/pjkfckr/롤케이크_자르기.py

- https://school.programmers.co.kr/learn/courses/30/lessons/132265
- 구현
- 티모님의 시간복잡도를 보고 도전의식으로 시간줄이기 돌입해봤습니다. 단 하나의 반복문을 사용하여 O(n)이 나오게 변경
-

[PGS] 난이도2 / 롤케이크 자르기 / 20분

---

leetcode/pjkfckr/Simplify_path.py

- https://leetcode.com/problems/simplify-path/?envType=problem-list-v2&envId=stack&difficulty=MEDIUM
- 스택, 문자열
- 문제를 들여다보면 간단하게 풀수있다.
-

[LTC] Medium / 경로설정 / 15분

---

leetcode/0chnxxx/Simplify_Path.kt

- https://leetcode.com/problems/simplify-path/description/?envType=problem-list-v2&envId=stack&difficulty=MEDIUM
- 스택
- 
-

[LTC] MEDIUM / Simplify Path / 53분

---

leetcode/BottlePumpkin/simplifyPath.py

캬
https://leetcode.com/problems/simplify-path/?envType=problem-list-v2&envId=stack&difficulty=MEDIUM
- 
STACK
-
어렵네 ㅋ 
- 
왤케 어려울까?
-

[LTC] MEDIUM / SimplifyPath / 50분

---

leetcode/yeongi/simply_path.js

https://leetcode.com/problems/simplify-path/description/?envType=problem-list-v2&envId=stack&difficulty=MEDIUM
스택 응용 문제
- 
-

[LTC] Medium / 경로설정 / 30분

---

programmers/0chnxxx/택배상자.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/131704
- 구현
- 프로그래머스는 import 를 넣어줘야한다..
-

[PGS] 난이도2 / 택배상자 / 13분

---

programmers/0chnxxx/롤케이크_자르기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/132265
- 구현
- 코드 라인 수를 줄였습니다!
-

[PGS] 난이도2 / 롤케이크 자르기 / 7분

---

programmers/0chnxxx/숫자_변환하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/154538
- BFS
- 처음에 3가지 연산을 함수 배열로 만들어서 재귀로 풀려고 시도했었다.
- 재귀로 풀었으면 스택오버플로우가 발생했겠지?
- 탐색은 BFS, DFS, DP를 먼저 떠올려봐야겠다.
-

[PGS] 난이도2 / 숫자 변환하기 / 13분

---

programmers/0chnxxx/삼각_달팽이.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/68645
- 구현
- 
-

[PGS] 난이도2 / 삼각 달팽이 / 30분

---

programmers/0chnxxx/연속된_부분_수열의_합.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/178870
- 투 포인터
- 
-

[PGS] 난이도2 / 연속된 부분 수열의 합 / 9분

---

programmers/0chnxxx/마법의_엘리베이터.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/148653
- 탐색
- 10^c 의 값들을 활용하는 부분을 나눗셈의 몫과 나머지로 활용하는걸 놓쳤다.
-

[PGS] 난이도2 / 마법의 엘리베이터 / 38분

---

programmers/0chnxxx/시소_짝꿍.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/152996
- 탐색
- 케이스가 많다면 중첩 반복문을 도는거보단 평면적으로 계산하는 것도 고려해야겠다.
-

[PGS] 난이도2 / 시소 짝꿍 / 39분

---

baekjoon/pjkfckr/계단오르기.py

- https://www.acmicpc.net/problem/2579
- 브루트포스
- 처음엔 비효율적인 itertools.product 를 활용하여 모든 수의 합을 다 구해서 작성했지만, 시간초과로 브루트포스로 변경
-

[BOJ] 난이도1.5 / 계단오르기 / 35분

---

programmers/0chnxxx/추억_점수.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/176963
- 구현
- 
-

[PGS] 난이도1 / 추억 점수 / 20분

---

baekjoon/pjkfckr/트리_순회.py

- https://www.acmicpc.net/problem/1991
- 트리
- 전위순회 (Pre-order Traversal) 센터 -> 왼쪽 서브트리 -> 오른쪽 서브트리 CLR
- 중위순회 (In-order Traversal) 왼쪽 서브트리 -> 센터 -> 오른쪽 서브트리  LCR
- 후위순회 (Post-order Traversal) 왼쪽 서브트리 -> 오른쪽 서브트리 -> 센터  LRC
- 재귀의 순서에 따라 순회하는 방법이 다른것을 배웠다.
-

[BOJ] 난이도1.5 / 트리순회 / 30분

---

programmers/0chnxxx/카드_뭉치.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/159994
- 구현
- 
-

[PGS] 난이도1 / 카드 뭉치 / 10분

---

programmers/0chnxxx/덧칠하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/161989
- 구현
- 
-

[PGS] 난이도1 / 덧칠하기 / 13분

---

programmers/0chnxxx/대충_만든_자판.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/160586
- 구현
- 
- 시간 복잡도가 O(10^8)가 나오게 된다..
- 다행히 범위가 100개씩이라서 시간초과는 안뜨는거 같지만
- 탐색 알고리즘을 사용하면 더 줄일 수 있을 것 같다.

[PGS] 난이도1 / 대충 만든 자판 / 18분

---

baekjoon/pjkfckr/트리의_부모_찾기.py

- https://www.acmicpc.net/problem/11725
- 트리, 탐색
- 단순하게 트리를 만드는 방법을 생각하고 만들었지만, 탐색하는 부분에서 많이 막혀서 결국 방법을 검색했다.
- BFS(너비 우선 탐색)을 선택한 이유는 트리구조에서 효율적으로 탐색을 하고, 부모-자식 관계를 정확히 파악하는데 적합.
-

[BOJ] 난이도2 / 트리의 부모 찾기 / 40분

---

programmers/pjkfckr/게임_맵_최단거리.py

- https://school.programmers.co.kr/learn/courses/30/lessons/1844
- 격자탐색(BFS)
- 격자를 탐색하는 기본 소스코드에서 distance 라는 거리를 추가하여 어느정도 풀수있었다.
```python
def matrix_bfs():
q = deque([[0, 0]])
seen = [[0] * 7 for _ in range(5)]
seen[0][0] = 1
while q:
[ci, cj] = q.popleft()
matrix[ci][cj] = 9
for k in range(4):
ni = ci + di[k]
nj = cj + dj[k]
if not (0 <= ni < 5 and 0 <= nj < 7):
continue
if matrix[ni][nj] != 1:
continue
if seen[ni][nj] == 1:
continue
seen[ni][nj] = 1
q.append([ni, nj])
```
-

[PGS] 난이도2 / 게임 맵 최단거리 / 37분

---

programmers/0chnxxx/바탕화면_정리.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/161990
- 구현
- 
-

[PGS] 난이도1 / 바탕화면 정리 / 7분

---

programmers/0chnxxx/달리기_경주.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/178871
- 구현
- 
-

[PGS] 난이도1 / 달리기 경주 / 11분

---

programmers/0chnxxx/공원_산책.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/172928
- 구현
- 
-

[PGS] 난이도1 / 공원 산책 / 18분

---

programmers/pjkfckr/카펫.py

- https://school.programmers.co.kr/learn/courses/30/lessons/42842
- 완전탐색
- 완전탐색은 브루트포스로 생각해도 된다.
- 다양한 풀이가 존재함.
```python
def solution(brown, yellow):
total = brown + yellow
for i in range(1, int(yellow**0.5) + 1):
if yellow % i == 0:
width = yellow // i + 2
height = i + 2
if width * height == total:
return [width, height]
return []
```
```python
import math
def solution(brown, yellow):
w = ((brown + 4) / 2 + math.sqrt(((brown + 4) / 2) ** 2 - 4 * (brown + yellow))) / 2
h = (brown + yellow) / w
return [int(w), int(h)]
```
-

[PGS] 난이도2 / 카펫 / 45분

---

goorm/0chnxxx/0_채우기.kt

- https://level.goorm.io/exam/175011/0-%EC%B1%84%EC%9A%B0%EA%B8%B0/quiz/1
- 구현
- 
-

[GRM] 난이도2 / 0 채우기 / 7분

---

goorm/0chnxxx/과일_구매.kt

- https://level.goorm.io/exam/195697/%EA%B3%BC%EC%9D%BC-%EA%B5%AC%EB%A7%A4/quiz/1
- 구현
- 
-

[GRM] 난이도2 / 과일 구매 / 15분

---

goorm/0chnxxx/발전기_2.kt

- https://level.goorm.io/exam/195695/%EB%B0%9C%EC%A0%84%EA%B8%B0-2/quiz/1
- 탐색(BFS)
- 
-

[GRM] 난이도2 / 발전기 (2) / 53분

---

leetcode/pjkfckr/정렬된배열에서_첫번쨰와바지막위치찾기.py

- https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/
- 이진탐색 O(logN)
- 파이썬에서는 이진탐색을 지원하는 내장함수가 존재
- solution 함수는 내장함수를 사용한 코드
- solution_2 함수는 이진탐색을 구현한 코드
-

[LCT] 난이도1.5 / 요소찾기 / 20분

---

goorm/0chnxxx/연합.kt

- https://level.goorm.io/exam/195698/%EC%97%B0%ED%95%A9/quiz/1
- 탐색(Union-Find)
- Union-Find 알고리즘을 공부할 수 있었다.
-

[GRM] 난이도2 / 연합 / 61분

---

goorm/pjkfckr/인공지능_청소기.py

- https://level.goorm.io/exam/43068/1a-%EC%9D%B8%EA%B3%B5%EC%A7%80%EB%8A%A5-%EC%B2%AD%EC%86%8C%EA%B8%B0/quiz/1
- 구현
- 해당 문제는 좌표를 다루기때문에 BFS(너비 우선 탐색으로 문제를 풀었지만, 끝내 테스트 케이스를 넘지 못했다.
- 그래서 찾아본 결과 `맨허튼 거리` 라는 알고리즘이 존재했다.
- 둘의 차이
BFS 는 모든 가능한 경로를 탐색하는 그래프 탐색 알고리즘이기에 시간 복잡도 증가로 대규모 데이터가 input으로 들어오면 timeout 발생
맨허튼 거리 알고리즘은 두 점 사이의 최단 거리를 직접 계산하는 수학적 접근 방식 O(1) 로 매우 효율적 
로직만 보더라도 반복문이 없다.
맨허튼 거리는 격자구조(상, 하, 좌, 우)에 효율적
-

[GRM] 난이도1 / 인공지능 청소기 / 35분

---

goorm/0chnxxx/발전기.kt

- https://level.goorm.io/exam/195694/%EB%B0%9C%EC%A0%84%EA%B8%B0/quiz/1
- 탐색(BFS)
- 
-

[GRM] 난이도2 / 발전기 / 19분

---

leetcode/yeongi/난이도2_아름다운숫자.js

[LCT] 난이도2 / 아름다운숫자 만들기 / 20분

---

goorm/pjkfckr/카드_모으기.py

- https://level.goorm.io/exam/175909/%EC%B9%B4%EB%93%9C-%EB%AA%A8%EC%9C%BC%EA%B8%B0/quiz/1
- 해시
- enumerate 를 활용하여 value 와 index 1부터 시작하여 동시에 가져오며 카드 종류와 해시에 담긴 카드 종류가 동일하게 되면 얼리리턴
-

[GRM] 난이도 2(쉬움) / 카드 모으기 / 13분

---

leetcode/yeongi/난이도2_FindifArrayCanBeSorted.js

- 리트코드 데일리 
- 구현
- 기능별로 함수를 나누면 더욱 가독성이 좋아지는것 같다.
-

[LCT] 난이도2 /  정렬가능한 배열 찾기 / 30분

---

goorm/0chnxxx/Queue.kt

- https://level.goorm.io/exam/175241/queue/quiz/1
- 구현
- 
-

[GRM] 난이도2 / Queue / 10분

---

goorm/0chnxxx/구름_아이돌.kt

- https://level.goorm.io/exam/191018/%EA%B5%AC%EB%A6%84-%EC%95%84%EC%9D%B4%EB%8F%8C/quiz/1
- 구현
- 
-

[GRM] 난이도2 / 구름 아이돌 / 10분

---

programmers/pjkfckr/H-Index.py

- https://school.programmers.co.kr/learn/courses/30/lessons/42747
- 정렬
- H-Index 라는 개념이 실제로 존재하는것을 처음알았다.
- https://namu.wiki/w/h%20%EC%9D%B8%EB%8D%B1%EC%8A%A4
-

[PGS] 난이도 2 / H-Index / 20분

---

goorm/0chnxxx/M배_배열.kt

- https://level.goorm.io/exam/174909/m%EB%B0%B0-%EB%B0%B0%EC%97%B4/quiz/1
- 쉬운 구현
- 
-

[GRM] 난이도2 / M배 배열 / 5분

---

goorm/0chnxxx/구름이의_여행.kt

- https://level.goorm.io/exam/159546/%EA%B5%AC%EB%A6%84%EC%9D%B4%EC%9D%98-%EC%97%AC%ED%96%89/quiz/1
- 탐색(DFS)
- 리스트 배열을 통해 양방향 정보를 담고
- DFS로 깊이 우선 탐색을 통해 가능 여부를 찾았다.
-

[GRM] 난이도2 / 구름이의 여행 / 31분

---

goorm/pjkfckr/폭탄_구현하기.py

- https://level.goorm.io/exam/159666/%ED%8F%AD%ED%83%84-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0/quiz/1
- 구현
- 이전에 푼 폭탄 구현하기(2) 문제에서 조건이 빠진 간단한 구현문제
- booms 를 받는 곳에서 tuple로 매핑하여 메모리 사용량을 줄이고 속도개선
- boom에서 인덱스로 접근하는것을 직접 언패킹하여 인덱싱 연산 개선
-

[GRM] 난이도 2 / 폭탄 구현하기 / 10분

---

goorm/pjkfckr/딱지놀이.py

- https://level.goorm.io/exam/48130/%EB%94%B1%EC%A7%80%EB%86%80%EC%9D%B4/quiz/1
- 구현
- 입력에 대한 조건을 제대로 읽지않아 i번째 라운드에서 A, B 의 딱지 값에 대한 첫번째 값이 딱지의 개수인지 몰라 좀더 해맷다.
-

[GRM] 난이도 1 / 딱지놀이 / 25분

---

goorm/0chnxxx/큰_수식_찾기.kt

- https://level.goorm.io/exam/174717/%ED%81%B0-%EC%88%98%EC%8B%9D-%EC%B0%BE%EA%B8%B0/quiz/1
- 구현
- 
- 연산기호별로 특정 우선순위가 주어지는 케이스에선 어떻게 해야할까..?

[GRM] 난이도2 / 큰 수식 찾기 / 37분

---

goorm/0chnxxx/파손된_램.kt

- https://level.goorm.io/exam/49074/%ED%8C%8C%EC%86%90%EB%90%9C-%EB%9E%A8/quiz/1
- 구현
- 2의 제곱수인지 판별하는 방법을 알았다!
- 2의 제곱수는 비트로 표현했을 때 하나의 비트만 1인 숫자들이다. (규칙)
- 그래서 1을 뺀 수와 and 연산을 했을 때 0이 나와야 2의 제곱수인 것이다.
-

[GRM] 난이도2 / 파손된 램 / 11분

---

goorm/0chnxxx/밀도_정렬.kt

- https://level.goorm.io/exam/174784/%EB%B0%80%EB%8F%84-%EC%A0%95%EB%A0%AC/quiz/1
- 구현
- 코틀린의 정렬 메서드는 자바보다 훨씬 나은거 같다..
-

[GRM] 난이도2 / 밀도 정렬 / 10분

---

goorm/pjkfckr/장마.py

- https://level.goorm.io/exam/194982/%EC%9E%A5%EB%A7%88/quiz/1
- 구현
- 3일째 배수 시스템 에서 계속해서 같은 집을 배수 하는게 아닌 한번만 배수한다는것을 늦게 알게되었다.
- clear_list를 배수시스템이 동작하고 나서 clear 를 하지않아서 원하는데로 동작하지 않았다.
-

[GRM] 난이도 2 / 장마 / 35분

---

goorm/0chnxxx/명령_미로_탈출.kt

- https://level.goorm.io/exam/210125/%EB%AA%85%EB%A0%B9-%EB%AF%B8%EB%A1%9C-%ED%83%88%EC%B6%9C/quiz/1
- 구현
- 
-

[GRM] 난이도2 / 명령 미로 탈출 / 19분

---

goorm/pjkfckr/뭉친_K.py

- https://level.goorm.io/exam/177478/%EB%AD%89%EC%B9%9C-k/quiz/1
- 완전탐색
- 처음에 접근하는 방식에서 상하좌우를 보고 BFS 를 떠올려 적용했지만, 그 이후로 접근방식 자체가 떠오르지 않았다.
- 아무래도 문제에 대해 이해도가 아직까지 딸린느낌
-

[GRM] 난이도 3 / 뭉친K / 50분

---

goorm/0chnxxx/개발자_지망생_구름이의_취업_뽀개기.kt

- https://level.goorm.io/exam/208932/%EA%B0%9C%EB%B0%9C%EC%9E%90-%EC%A7%80%EB%A7%9D%EC%83%9D-%EA%B5%AC%EB%A6%84%EC%9D%B4%EC%9D%98-%EC%B7%A8%EC%97%85-%EB%BD%80%EA%B0%9C%EA%B8%B0/quiz/1
- 재밌는 구현 문제
- 
-

[GRM] 난이도2 / 개발자 지망생 구름이의 취업 뽀개기 / 27분

---

goorm/0chnxxx/카드_모으기.kt

- https://level.goorm.io/exam/175909/%EC%B9%B4%EB%93%9C-%EB%AA%A8%EC%9C%BC%EA%B8%B0/quiz/1
- 구현
- List 또는 Array에서의 contains() 메서드는 O(N) 이다.
- 하지만, Set(HashSet)에서의 contains() 메서드는 O(1) 이다.
-

[GRM] 난이도2 / 카드 모으기 / 28분

---

goorm/0chnxxx/폴더_폰_자판.kt

- https://level.goorm.io/exam/159544/%ED%8F%B4%EB%8D%94-%ED%8F%B0-%EC%9E%90%ED%8C%90/quiz/1
- 구현
- 접근방식은 틀리지 않았는데 반복 구조를 % 연산으로 줄이려는게 잘 안 돼서 오래 걸렸다..
-

[GRM] 난이도2 / 폴더 폰 자판 / 73분

---

goorm/pjkfckr/밀도_정렬.py

- https://level.goorm.io/exam/174784/%EB%B0%80%EB%8F%84-%EC%A0%95%EB%A0%AC/quiz/1
- 정렬
- lambda 식으로 각 요소 별 정렬 기준으로 세워서 간단하게 처리 가능
- 음수로 정렬하는 경우 내림차순, 양수는 오름차순 으로 각 요소 설정
-

[GRM] 난이도 2 / 밀도_정렬 / 25분

---

goorm/0chnxxx/개미와_진딧물.kt

- https://level.goorm.io/exam/167338/%EA%B0%9C%EB%AF%B8%EC%99%80-%EC%A7%84%EB%94%A7%EB%AC%BC/quiz/1
- 구현
- 맨해튼 거리를 한 번 더 복습하였다.
-

[GRM] 난이도2 / 개미와 진딧물 / 22분

---

goorm/pjkfckr/발전기.py

- https://level.goorm.io/exam/195694/%EB%B0%9C%EC%A0%84%EA%B8%B0/quiz/1
- 탐색
- 전형적인 bfs 문제로 복기하기 좋았다.
-

[GRM] 난이도 2 / 발전기 / 25분

---

leetcode/yeongi/난이도2_폭탄해독.js

- 리트코드 데일리
- 배열 ?
- 문제를 꼼꼼히 읽자 .. ( 원형 배열 )
-

[LTC] 난이도1 / 폭탄해독 / 30분

---

goorm/pjkfckr/발전기_2.py

- https://level.goorm.io/exam/195695/%EB%B0%9C%EC%A0%84%EA%B8%B0-2/quiz/1
- BFS
- 상하좌우 로테이션 전에 중심점을 True 처리 하는것을 까먹어서 몇번 찾아봄.
- count 와 type 을 구분해서 저장하는 방식을 생각하는데에 많은 시간이 소요됨
-

[GRM] 난이도 2 / 발전기 2 / 40분

---

goorm/pjkfckr/완벽한_햄버거_만들기.py

- https://level.goorm.io/exam/195686/%EC%99%84%EB%B2%BD%ED%95%9C-%ED%96%84%EB%B2%84%EA%B1%B0-%EB%A7%8C%EB%93%A4%EA%B8%B0/quiz/1
- 구현
- 문제를 풀었을때 간단하게 내림차순 정렬 후 풀이를 시작했지만, 추후에는 아닌것으로 확인.
- "피크 검사( Peak Check)" 또는 "산 모양 검사(Mountain Shape Check)" 알고리즘을 알게 되었다.
- 피크검사라 함은 배열에서 특정 패턴을 찾는 방법.
- 최대값 찾기 -> 양방향 검사 -> 단조성 검사 를 통해 값을 도출해나가게 됩니다.
-

[GRM] 난이도 2 / 완벽한 햄버거 만들기 / 40분

---

goorm/0chnxxx/작은_노드.kt

- https://level.goorm.io/exam/195696/%EC%9E%91%EC%9D%80-%EB%85%B8%EB%93%9C/quiz/1
- 탐색(양방향 그래프)
- "번호가 가장 작은 노드로 이동한다"
- 문제를 잘 읽자...
-

[GRM] 난이도3 / 작은 노드 / 57분

---

goorm/0chnxxx/대체_경로.kt

- https://level.goorm.io/exam/195701/%EB%8C%80%EC%B2%B4-%EA%B2%BD%EB%A1%9C/quiz/1
- 특정 조건이 있는 양방향 그래프 탐색 (BFS)
- 
-

[GRM] 난이도3 / 대체 경로 / 30분

---

goorm/pjkfckr/제곱암호.py

- https://level.goorm.io/exam/162066/%EC%A0%9C%EA%B3%B1%EC%95%94%ED%98%B8/quiz/1
- 문자열
- 알파벳이 z에서 다시 a로 돌아가야하는 조건을 만족시키는게 오래걸렸다.
- chr 과 ord 를 사용하여 풀수있고, string 이라는 내장모듈에서 알파벳배열의 인덱스를 통해서도 구할 수 있다.
- 두가지 방법을 제시
-

[GRM] 난이도 2 / 제곱암호 / 35분

---

goorm/pjkfckr/UXUI_디자이너.py

- https://level.goorm.io/exam/163020/uxui-%EB%94%94%EC%9E%90%EC%9D%B4%EB%84%88/quiz/1
- 정렬
- 2중배열 평탄화 하는 방법을 찾아서 itertools의 chain을 사용하여 K를 언패킹 후 연결하는 방식으로 1차원 배열로 변경
- Counter 내장함수를 사용하여 이벤트의 수 를 확인 후 most_common 으로 빈도수로 변경 후 max값을 비교하여 출력
-

[GRM] 난이도 2 / UXUI 디자이너 / 20분

---

goorm/0chnxxx/RGB_주차장.kt

- https://level.goorm.io/exam/177463/rgb-%EC%A3%BC%EC%B0%A8%EC%9E%A5/quiz/1
- DP
- 
-

[GRM] 난이도3 / RGB 주차장 / 27분

---

goorm/pjkfckr/Dead_or_Arrive.py

- https://level.goorm.io/exam/152114/%ED%98%84%EB%8C%80%EB%AA%A8%EB%B9%84%EC%8A%A4-%EC%98%88%EC%84%A0-dead-or-arrive/quiz/1
- 구현
- 모든 데이터를 받고나서 정렬을 실행하니 타임아웃이 발생하여 모든 데이터가 아닌 조건에 있는 차량만 검사하여 메모리 및 속도 개선
-

[GRM] 난이도 2 / Dead or Arrive / 38분

---

goorm/pjkfckr/성적표.py

- https://level.goorm.io/exam/171280/%EC%84%B1%EC%A0%81%ED%91%9C/quiz/1
- 구현
- 단순 구현으로 총점과 과목별 시험 횟수를 구하고, 해당 데이터를 조건에 맞춰 평균이 높은 과목을 구한다.
-

[GRM] 난이도 2 / 성적표 / 30분

---

goorm/pjkfckr/개명_찬스.py

- https://level.goorm.io/exam/49069/%EC%B6%9C%EC%84%9D%EB%B6%80/quiz/1
- 문자열
- 제거할 index를 찾지못하면 마지막 문자열을 지움으로써 사전순으로 최저그이 개명 결과를 도출할 수 있다.
-

[GRM] 난이도 2 / 출석부 / 20분

---

goorm/0chnxxx/수_이어_붙이기.kt

- https://level.goorm.io/exam/161273/%EC%88%98-%EC%9D%B4%EC%96%B4%EB%B6%99%EC%9D%B4%EA%B8%B0/quiz/1
- 재귀순열 + 구현
- 오랜만에 순열을 보았습니다.
-

[GRM] 난이도3 / 수 이어 붙이기 / 39분

---

goorm/0chnxxx/순환하는_수로.kt

- https://level.goorm.io/exam/159547/%EC%88%9C%ED%99%98%ED%95%98%EB%8A%94-%EC%88%98%EB%A1%9C/quiz/1
- DFS
- 
- 재귀는 직관적이지 않아서 어렵다..

[GRM] 난이도3 / 순환하는 수로 / 60분

---

goorm/0chnxxx/뭉친_K.kt

- https://level.goorm.io/exam/177478/%EB%AD%89%EC%B9%9C-k/quiz/1
- 탐색 (BFS)
- 아.. 좌표 숫자 장난질 진짜..
- 테스트케이스 1번에 x, y 좌표 1, 2가 인덱스 기준인줄 알고 문제를 읽었다가 10분동안 해맸다..
-

[GRM] 난이도3 / 뭉친 K / 41분

---

goorm/0chnxxx/공통_명단_찾기.kt

- https://level.goorm.io/exam/347814/%EA%B3%B5%ED%86%B5-%EB%AA%85%EB%8B%A8-%EC%B0%BE%EA%B8%B0/quiz/1
- 구현
- 
-

[GRM] 난이도2 / 공통 명단 찾기 / 6분

---

goorm/pjkfckr/이진수_정렬.py

- https://level.goorm.io/exam/195687/%EC%9D%B4%EC%A7%84%EC%88%98-%EC%A0%95%EB%A0%AC/quiz/1
- 정렬
- Python 의 sorted 함수와 정렬 기준을 여러개 주기위해 lambda 를 사용하여 순차적인 조건에 맞는 정렬을 진행 음수 표시는 내림차순의 뜻, 여러 조건이기에 각 조건마다 내림차순인지 오름차순인지 정할 수 있음
-

[GRM] 난이도 2 / 이진수 정렬 / 20분

---

goorm/0chnxxx/작업_주기_맞추기.kt

- https://level.goorm.io/exam/347932/%EC%9E%91%EC%97%85-%EC%A3%BC%EA%B8%B0-%EB%A7%9E%EC%B6%94%EA%B8%B0/quiz/1
- 수학 (최소공배수, 최대공약수)
- 
-

[GRM] 난이도2 / 작업 주기 맞추기 / 11분

---

goorm/pjkfckr/구름_찾기_깃발.py

- https://level.goorm.io/exam/195689/%EA%B5%AC%EB%A6%84-%EC%B0%BE%EA%B8%B0-%EA%B9%83%EB%B0%9C/quiz/1
-bfs 로 생각했지만, 단순 배열 조작입니다.
- 상하좌우 뿐 아니라 각 대각선을 조작하는 걸 알게 되었다.
-

[GRM] 난이도 2 / 구름 찾기 깃발 / 20분

---

goorm/0chnxxx/카드_찾기.kt

- https://level.goorm.io/exam/347956/%EC%B9%B4%EB%93%9C-%EC%B0%BE%EA%B8%B0/quiz/1
- 구현?.. (너무 쉬움)
- 
-

[GRM] 난이도2 / 카드 찾기 / 2분

---

goorm/0chnxxx/고대_문자2.kt

- https://level.goorm.io/exam/347908/%EA%B3%A0%EB%8C%80-%EB%AC%B8%EC%9E%902/quiz/1
- DP
- 
-

[GRM] 난이도3 / 고대 문자2 / 45분

---

goorm/0chnxxx/인기_매뉴.kt

- https://level.goorm.io/exam/347878/%EC%9D%B8%EA%B8%B0-%EB%A9%94%EB%89%B4/quiz/1
- 기본 정렬
- 
-

[GRM] 난이도2 / 인기 매뉴 / 7분

---

goorm/0chnxxx/크리스마스_할인이벤트.kt

- https://level.goorm.io/exam/348656/%ED%81%AC%EB%A6%AC%EC%8A%A4%EB%A7%88%EC%8A%A4-%ED%95%A0%EC%9D%B8%EC%9D%B4%EB%B2%A4%ED%8A%B8/quiz/1
- 정렬
- 
-

[GRM] 난이도2 / 크리스마스 할인이벤트 / 32분

---

goorm/0chnxxx/자동차_경주.kt

- https://level.goorm.io/exam/348612/%EC%9E%90%EB%8F%99%EC%B0%A8-%EC%86%8D%EB%8F%84/quiz/1
- 구현
- Kotlin의 List 중 drop()은 해당 요소가 없는 새로운 List로 복사하는 방식이기 때문에 느리다.
-

[GRM] 난이도2 / 자동차 속도 / 35분

---

goorm/pjkfckr/물통.py

- https://level.goorm.io/exam/48146/%EB%AC%BC%ED%86%B5/quiz/1
- BFS
- BFS 를 사용함과 동시에 구현이 들어가서 채우고 이동하는 로직을 어떻게 해야할지 감을 못잡고있었다.
-

[GRM] 난이도 3 / 물통 / 55분

---

goorm/0chnxxx/정확한_우유_구매.kt

- https://level.goorm.io/exam/348610/%EC%A0%95%ED%99%95%ED%95%9C-%EC%9A%B0%EC%9C%A0-%EA%B5%AC%EB%A7%A4/quiz/1
- 투 포인터
- 
-

[GRM] 난이도2 / 정확한 우유 구매 / 12분

---

programmers/0chnxxx/네트워크.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/43162
- 탐색 DFS/BFS
- 
-

[PGS] Lv3 / 네트워크 / 14분

---

leetcode/pjkfckr/Merge_Intervals.py

- https://leetcode.com/problems/merge-intervals/description/
- 배열
- 문제 자체가 간단해보이지만 간단하지 않은 것은 배열 자체 인덱스를 접근하여 데이터를 변경하거나 비교하기에 다소 햇갈릴 수 있음
-

[LTC] 난이도 2 / Merge Interval / 25분

---

programmers/0chnxxx/이중우선순위큐.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42628
- PriorityQueue 지만 List로 구현한..
- 
-

[PGS] Lv3 / 이중우선순위큐 / 36분

---

leetcode/pjkfckr/Pascal's_Triangle.py

- https://leetcode.com/problems/pascals-triangle/description/
- 배열
- 
-

[LTC] 난이도 1 / Pascal's Triangle / 10분

---

programmers/0chnxxx/단어_변환.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/43163
- 탐색 (BFS)
- 
- 프로그래머스는 도대체 왜 Kotlin 버전을 안 올려주세요?.. 아니면 import라도 할 수 있게 해주세요..

[PGS] Lv3 / 단어 변환 / 42분

---

goorm/pjkfckr/주차시스템.py

- https://level.goorm.io/exam/152115/%ED%98%84%EB%8C%80%EB%AA%A8%EB%B9%84%EC%8A%A4-%EC%98%88%EC%84%A0-%EC%A3%BC%EC%B0%A8%EC%8B%9C%EC%8A%A4%ED%85%9C/quiz/1
- 탐색
- 글에서 나온 그룹이라는 단어에 꽂혀서 그룹을 만들다가 배열에 append 하는 부분에서 Timeout이 발생, 이를 구하지않고 단순히 점수만 구하도록 변경하여 풀이 완료
-

[GRM] 난이도 3 / 주차시스템 / 45분

---

programmers/0chnxxx/베스트앨범.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42579
- 해시
- 
-

[PGS] Lv3 / 베스트앨범 / 25분

---

programmers/pjkfckr/단어_변환.py

- https://school.programmers.co.kr/learn/courses/30/lessons/43163
- BFS
- 처음에는 모든 알파벳을 비교하여 코드를 작성했지만, 한 문제에서 실패하는것을 보고
다른 방법을 찾던 중, 현재 단어와 한글자만 다른 단어를 찾는 조건문을 넣어 최적화 시킬 수 있었다.
-

[PGS] 난이도 3 / 단어 변환 / 40분

---

programmers/pjkfckr/더_맵게.py

- https://school.programmers.co.kr/learn/courses/30/lessons/42626
- 힙
- 힙의 기초를 배우는 문제
-

[GRM] 난이도 2 / 더 맵게 / 25분

---

programmers/0chnxxx/큰_수_만들기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42883
- 그리디
- 
-

[PGS] Lv2 / 큰 수 만들기 / 10분

---

programmers/0chnxxx/전력망을_둘로_나누기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/86971
- 탐색
- 
-

[PGS] Lv2 / 전력망을 둘로 나누기 / 36분

---

leetcode/pjkfckr/Kth_Largest_Element_in_an_Array.py

- https://leetcode.com/problems/kth-largest-element-in-an-array/description/
- Heap
- 선 정렬을 하지 않고, heap 을 사용하여 "-"를 사용하여 정렬이 heap에서 되게끔 코드를 작성후 K  - 1 만큼의 작은 수를 빼면 원하는 위치의 큰 수를 구할 수 있다.
-

[LTC] 난이도 2 / Kth Largest Element in an Array / 15분

---

programmers/0chnxxx/불량_사용자.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/64064
- 탐색 (백트래킹)
- 
-

[PGS] Lv3 / 불량 사용자 / 49분

---

programmers/pjkfckr/주식가격.py

- https://school.programmers.co.kr/learn/courses/30/lessons/42584?language=python3
- 스택
- 
-

[PGS] 난이도 2 / 주식가격 / 10분

---

programmers/0chnxxx/숫자_카드_나누기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/135807
- 최대공약수(유클리드 호제법)
- 
-

[PGS] Lv2 / 숫자 카드 나누기 / 25분

---

leetcode/pjkfckr/Container_With_Most_Water.py

- https://leetcode.com/problems/container-with-most-water/description/
- 투 포인터
- 배열에서 왼쪽과 오른쪽이 서로 상관관계를 가지고 이 사이의 무언가를 찾을때는 투 포인터 알고리즘이 효과적으로 사용될 수 있다는것을 알게 되었다.
-

[LTC] 난이도 2 / Container With Most Water / 35분

---

programmers/0chnxxx/배달.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/12978
- 탐색 (다익스트라)
- 그래프의 경로 최단 거리를 찾을 땐? 다익스트라!
-

[PGS] Lv2 / 배달 / 36분

---

programmers/0chnxxx/미로_탈출.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/159993
- 탐색 (BFS)
- 
-

[PGS] Lv2 / 미로 탈출 / 26분

---

leetcode/pjkfckr/Search_a_2D_Matrix_2.py

- https://leetcode.com/problems/search-a-2d-matrix-ii/description/
- 이진 탐색
- 두가지의 버전으로 작성해보았는데, 하나는 O(m + n) 의 시간복잡도와 O(m * log(n)) 의 시간복잡도를 가지는 버전이 있습니다.
- `search_matrix` 함수는 "search space reduction" 이라는 기법으로 문제의 복잡성을 줄이고 최적의 해를 더 효율적으로 찾는 방법 입니다.
- `binary_search` 함수는 파이썬의 내장함수인 "bisect" 를 활용하여 타겟의 데이터가 들어갈 위치를 왼쪽 기준으로 찾고, target과 동일한 값이 존재할 경우 "bisect_left"를 활용하여 찾은 index의 위치가 target 의 값과 동일합니다.
-

[LTC] 난이도 2 / Search a 2D Matrix II / 35분

---

programmers/0chnxxx/보석_쇼핑.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/67258
- 슬라이딩 윈도우
- 
-

[PGS] Lv3 / 보석 쇼핑 / 29분

---

programmers/0chnxxx/무인도_여행.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/154540
- 탐색 (DFS)
- 
-

[PGS] Lv2 / 무인도 여행 / 23분

---

programmers/0chnxxx/리코쳇_로봇.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/169199
- 탐색 (BFS)
- 4방향으로 벽을 만날 때까지 미끄러지는 로직은 GPT의 도움을 받았다..
- 신기하다..!
-

[PGS] Lv2 / 리코쳇 로봇 / 22분

---

leetcode/pjkfckr/Restore_IP_Addresses.py

- https://leetcode.com/problems/restore-ip-addresses/description/
- 브루트포스
- 문자열을 조합하여 유효한 데이터 셋 만들기를 배운것 같다.
-

[LTC] 난이도 2 / Restore IP Addresses / 40분

---

programmers/0chnxxx/테이블_해시_함수.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/147354
- 구현
- 
-

[PGS] Lv2 / 테이블 해시 함수 / 10분

---

leetcode/pjkfckr/Jump_Game_II.py

- https://leetcode.com/problems/jump-game-ii/description/
- 동적 프로그래밍
- 아직 DP 식을 세우는것에 익숙하지가 않다. 분명 문제속에 DP식을 세울 수 있는 조건을 다 주는것은 맞다.
-

[LTC] 난이도 2 / Jump Game II / 35분

---

programmers/0chnxxx/섬_연결하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42861
- Union-Find
- 처음엔 최소 비용으로 간선 정렬 후 다리를 하나씩 추가할 때마다 BFS로 모든 노드가 연결되었는지 확인했다..
- 최소 비용을 찾기 위해선 불필요하게 모든 그래프를 그릴 필요가 없다는 것을 알게 되었다.
- 그리고 매번 BFS로 확인하는건 많은 양의 인풋에서는 비효율적인 시간복잡도를 만들게 된다.
-

[PGS] Lv3 / 섬 연결하기 / 29분

---

programmers/0chnxxx/가장_먼_노드.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/49189
- 탐색 (BFS)
- 
-

[PGS] Lv3 / 가장 먼 노드 / 11분

---

leetcode/pjkfckr/Unique_Binary_Search_Trees.py

- https://leetcode.com/problems/unique-binary-search-trees/description/
- DP
- 처음에는 문제 타이틀 그대로 Node 와 BST 를 만들어 문제 풀이를 진행하였으나 메모리 제한에 걸려 다른 방식을 찾아보았습니다.
- `카탈란 수` 라는것이 있었으며 이 문제는 AI와 함께 풀이를 진행하게 되었습니다.
-

[LTC] 난이도 2 / Unique Binary Search Trees / 55분

---

programmers/0chnxxx/징검다리_건너기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/64062
- 이진 탐색
- 처음에 이중 루프로 시간복잡도가 안좋게 작성했다.
- 탐색해야되는 범위가 클 땐 이진 탐색도 고려해보자.
-

[PGS] Lv3 / 징검다리 건너기 / 28분

---

programmers/0chnxxx/여행경로.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/43164
- 탐색 (DFS, 백트래킹)
- 
-

[PGS] Lv3 / 여행경로 / 43분

---

programmers/0chnxxx/디펜스_게임.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/142085
- 구현
- 
-

[PGS] Lv2 / 디펜스 게임 / 33분

---

programmers/0chnxxx/광물_캐기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/172927
- 그리디
- 
-

[PGS] Lv2 / 광물 캐기 / 76분

---

programmers/0chnxxx/입국심사.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/43238
- 이진 탐색
- 
-

[PGS] Lv3 / 입국심사 / 18분

---

programmers/0chnxxx/디스크_컨트롤러.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42627
- 우선순위 큐
- 
-

[PGS] Lv3 / 디스크 컨트롤러 / 48분

---

programmers/0chnxxx/이모티콘_할인행사.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/150368
- 백트래킹 & 조합
- 
-

[PGS] Lv2 / 이모티콘 할인행사 / 43분

---

programmers/0chnxxx/후보키.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42890
- 조합
- 
-

[PGS] Lv2 / 후보키 / 18분

---

programmers/0chnxxx/N-Queen.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/12952
- 백트래킹
- 
-

[PGS] Lv2 / N-Queen / 8분

---

programmers/0chnxxx/점_찍기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/140107
- 수학
- 점 (x,y)가 원점으로부터 거리가 d를 넘지 않는 조건은 𝑥^2 + 𝑦^2 ≤ 𝑑^2
-

[PGS] Lv2 / 점 찍기 / 20분

---

programmers/0chnxxx/과제_진행하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/176962
- 구현
- 
-

[PGS] Lv2 / 과제 진행하기 / 12분

---

programmers/0chnxxx/혼자서_하는_틱택토.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/160585
- 구현
- 
-

[PGS] Lv2 / 혼자서 하는 택틱토 / 19분

---

programmers/0chnxxx/두_원_사이의_정수_쌍.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/181187
- 수학
- 
-

[PGS] Lv2 / 두 원 사이의 정수 쌍 / 48분

---

programmers/0chnxxx/요격_시스템.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/181188
- 구현
- 
-

[PGS] Lv2 / 요격 시스템 / 13분

---

programmers/0chnxxx/양궁대회.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/92342
- 백트래킹
- 
-

[PGS] Lv2 / 양궁대회 / 40분

---

programmers/0chnxxx/조이스틱.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42860
- 그리디
- 
-

[PGS] Lv2 / 조이스틱 / 46분

---

programmers/0chnxxx/택배_배달과_수거하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/150369
- 구현
- 
-

[PGS] Lv2 / 택배 배달과 수거하기 / 41분

---

programmers/0chnxxx/부대복귀.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/132266
- 탐색
- 
-

[PGS] Lv3 / 부대복귀 / 44분

---

leetcode/pjkfckr/Sort_Colors.kt

- https://leetcode.com/problems/sort-colors/
- 정렬
- 주어지는 숫자는 0, 1, 2로 한정되어있고 이를 O(n) 으로 정렬하기위해 계수 정렬(counting sort) 를 사용해서 정렬
-

[LTC] 난이도 2 / Sort Colors / 10분

---

programmers/0chnxxx/경주로_건설.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/67259
- BFS
- 
-

[PGS] Lv3 / 경주로 건설 / 22분

---

leetcode/pjkfckr/ValidateBinarySearchTree.kt

- https://leetcode.com/problems/validate-binary-search-tree/description/
- Binary Search Tree
- 
-

[LTC] 난이도 2 / Validate Binary Search Tree / 35분

---

programmers/0chnxxx/순위.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/49191
- 그래프
- 플로이드-워셜 알고리즘은 모든 정점 쌍 간의 최단 경로나 연결 여부를 판별하는 데 유용한 알고리즘
- 이 문제에선 연결 여부를 판단하며 매개변수로 주어진 승패관계를 기반으로 확장 추론하였다. (A -> B -> C)
-

[PGS] Lv3 / 순위 / 37분

---

programmers/0chnxxx/가장_긴_팰린드롬.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/12904
- 구현
- 
-

[PGS] Lv3 / 가장 긴 팰린드롬 / 20분

---

programmers/0chnxxx/다단계_칫솔_판매.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/77486
- 탐색
- 
-

[PGS] Lv3 / 다단계 칫솔 판매 / 40분

---

programmers/0chnxxx/풍선_터트리기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/68646
- 구현
- 
-

[PGS] Lv3 / 풍선 터트리기 / 21분

---

programmers/0chnxxx/자물쇠와_열쇠.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/60059
- 구현
- 
-

[PGS] Lv3 / 자물쇠와 열쇠 / 52분

---

leetcode/pjkfckr/132Pattern.kt

- https://leetcode.com/problems/132-pattern/
- 배열
- 
-

[LTC] 난이도 2 / 132 Pattern / 10분

---

programmers/0chnxxx/합승_택시_요금.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/72413
- 다익스트라
- 
-

[PGS] Lv3 / 합승 택시 요금 / 56분

---

programmers/0chnxxx/파괴되지_않은_건물.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/92344
- 누적합
- 
-

[PGS] Lv3 / 파괴되지 않은 건물 / 58분

---

programmers/0chnxxx/표_편집.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/81303
- 구현
- 
-

[PGS] Lv3 / 표 편집 / 33분

---

programmers/0chnxxx/길_찾기_게임.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42892
- 이진 트리
- 
-

[PGS] Lv3 / 길 찾기 게임 / 40분

---

programmers/0chnxxx/퍼즐_게임_챌린지.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/340212
- 이진 탐색 & 구현
- 
-

[PGS] Lv2 / 퍼즐 게임 챌린지 / 29분

---

programmers/0chnxxx/양과_늑대.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/92343
- 이진 트리 & DFS
- 
-

[PGS] Lv3 / 양과 늑대 / 41분

---

programmers/0chnxxx/기둥과_보_설치.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/60061
- 구현
- 
-

[PGS] Lv3 / 기둥과 보 설치 / 38분

---

programmers/0chnxxx/광고_삽입.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/72414
- 슬라이딩 윈도우 & 누적합 & 구현
- 
-

[PGS] Lv3 / 광고 삽입 / 49분

---

programmers/0chnxxx/미로_탈출_명령어.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/150365
- DFS & 백트래킹
- 
-

[PGS] Lv3 / 미로 탈출 명령어 / 45분

---

programmers/0chnxxx/교점에_별_만들기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/87377
- 수학
- 직선을 나타내는 방정식 2개로 교점을 구하려면 행렬식을 사용하면 된다.
- (A1, B2, C1) 과 (A2, B2, C2)일 때
- x = (B1 * C2 - B2 * C1) / (A1 * B2 - A2 * B1)
- y = (A2 * C1 - A1 * C2) / (A1 * B2 - A2 * B1)
- 이 때 행렬식의 분모가 0이면 두 직선이 평행하거나 일치한다.
- 또한 일반 좌표계의 좌표를 2차원 배열로 옮길 땐 인덱스에 주의하자.
- 행은 음수 좌표를 0부터 시작하게끔 보정해야하며, 열은 위로 증가하는 값을 아래로 증가하게끔 보정해야한다.
-

[PGS] Lv2 / 교점에 별 만들기 / 35분

---

programmers/0chnxxx/외벽_점검.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/60062
- 순열 탐색
- 
-

[PGS] Lv3 / 외벽 점검 / 48분

---

programmers/0chnxxx/110_옮기기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/77886
- 구현
- 
-

[PGS] Lv2 / 110 옮기기 / 32분

---

programmers/0chnxxx/표현_가능한_이진트리.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/150367
- 이진 트리 & DFS
- 
-

[PGS] Lv3 / 표현 가능한 이진트리 / 43분

---

programmers/0chnxxx/충돌위험_찾기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/340211
- 구현
- 
-

[PGS] Lv2 / 충돌위험 찾기 / 91분

---

programmers/0chnxxx/스타_수열.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/70130
- 구현
- 
-

[PGS] Lv3 / 스타 수열 / 93분

---

programmers/0chnxxx/등산코스_정하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/118669
- BFS 기반 다익스트라
- 
-

[PGS] Lv3 / 등산코스 정하기 / 55분

---

programmers/0chnxxx/블록_이동하기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/60063
- BFS
- 2차원 배열에서 4방향 탐색에 회전까지 추가한 변형 문제
- 
-

[PGS] Lv3 / 블록 이동하기 / 59분

---

programmers/0chnxxx/도넛과_막대_그래프.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/258711
- 그래프 & BFS
- 
-

[PGS] Lv2 / 도넛과 막대 그래프 / 71분

---

programmers/0chnxxx/빛의_경로_사이클.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/86052
- 배열 탐색
- 토러스 구조는 배열의 끝까지 이동하면 다시 배열의 시작점으로 돌아오는 구조
- 0-based index에선 (x + dx + n) % n
- 1-based index에선 (x dx - 1 + n) % n + 1
-

[PGS] Lv2 / 빛의 경로 사이클 / 50분

---

programmers/0chnxxx/N으로_표현.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42895
- DP
- 
-

[PGS] Lv3 / N으로 표현 / 20분

---

programmers/0chnxxx/카운트_다운.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/131129
- DP
- 
-

[PGS] Lv3 / 카운트 다운 / 22분

---

programmers/0chnxxx/표_병합.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/150366
- 구현
- 
-

[PGS] Lv3 / 표 병합 / 66분

---

programmers/0chnxxx/모두_0으로_만들기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/76503
- 비재귀 DFS
- 재귀를 사용할 때 호출이 깊다면 스택을 이용해서 DFS를 구현할 수 있다.
- 방문한 경우 pop하고 방문하지 않은 경우 push하면 후위 순회로 처리할 수 있다.
-

[PGS] Lv3 / 모두 0으로 만들기 / 54분

---

programmers/0chnxxx/2차원_동전_뒤집기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/131703
- 2차원 배열
- 
-

[PGS] Lv3 / 2차원 동전 뒤집기 / 46분

---

programmers/0chnxxx/코딩_테스트_공부.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/118668
- DP
- 
-

[PGS] Lv3 / 코딩 테스트 공부 / 60분

---

programmers/0chnxxx/지게차와_크레인.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/388353
- 2차원 배열 위주의 구현
- 
-

[PGS] Lv2 / 지게차와 크레인 / 155분

---

programmers/0chnxxx/등대.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/133500
- DFS & DP
- 
-

[PGS] Lv3 / 등대 / 29분

---

programmers/0chnxxx/공_이동_시뮬레이션.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/87391
- 구현
- 
-

[PGS] Lv3 / 공 이동 시뮬레이션 / 75분

---

programmers/0chnxxx/당구_연습.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/169198
- 수학
- 
-

[PGS] Lv2 / 당구 연습 / 35분

---

programmers/0chnxxx/매칭_점수.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/42893
- 정규 표현식
- 
-

[PGS] Lv3 / 매칭 점수 / 104분

---

programmers/0chnxxx/카드_짝_맞추기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/72415
- BFS + DFS + 백트래킹
- 
-

[PGS] Lv3 / 카드 짝 맞추기 / 151분

---

programmers/0chnxxx/주사위_고르기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/258709
- 조합
- 
-

[PGS] Lv3 / 주사위 고르기 / 80분

---

programmers/0chnxxx/n+1_카드게임.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/258707
- 구현
- 
-

[PGS] Lv3 / n+1 카드게임 / 78분

---

programmers/0chnxxx/택배_상자_꺼내기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/389478
- 구현
- 
-

[PGS] Lv1 / 택배 상자 꺼내기 / 55분

---

programmers/0chnxxx/동영상_재생기.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/340213
- 구현
- 
-

[PGS] Lv1 / 동영상 재생기 / 57분

---

programmers/0chnxxx/가장_많이_받은_선물.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/258712
- 구현
- 
-

[PGS] Lv1 / 가장 많이 받은 선물 / 45분

---

goorm/0chnxxx/Dead_or_Arrive.kt

- https://level.goorm.io/exam/152114/%ED%98%84%EB%8C%80%EB%AA%A8%EB%B9%84%EC%8A%A4-%EC%98%88%EC%84%A0-dead-or-arrive/quiz/1
- 구현
- 
-

[GRM] Lv2 / Daed or Arrive / 25분

---

programmers/0chnxxx/비밀_코드_해독.kt

- https://school.programmers.co.kr/learn/courses/30/lessons/388352
- 재귀 DFS + 백트래킹을 사용한 조합
- 
-

[PGS] Lv2 / 비밀 코드 해독 / 41분

---

leetcode/0chnxxx/Two_Sum.kt

- https://leetcode.com/problems/two-sum/submissions/1565613475/
- 배열
- 
-

[LTC] Lv1 / Two Sum / 14분

---

leetcode/0chnxxx/Add_Two_Numbers.kt

- https://leetcode.com/problems/add-two-numbers/description/
- 구현
- 
-

[LTC] Lv2 / Add Two Numbers / 23분

---

leetcode/0chnxxx/Longest_Substring_Without_Repeating_Characters.kt

- https://leetcode.com/problems/longest-substring-without-repeating-characters/description/
- 윈도우 슬라이딩
- 
-

[LTC] Lv2 / Longest Substring Without Repeating Characters / 32분

---

leetcode/0chnxxx/Longest_Palindromic_Substring.kt

- https://leetcode.com/problems/longest-palindromic-substring/description/
- DP
- 
-

[LTC] Lv2 / Longest Palindromic Substring / 31분

---

leetcode/0chnxxx/Zigzag_Conversion.kt

- https://leetcode.com/problems/zigzag-conversion/submissions/1569913275/
- 구현
- 
-

[LTC] Lv2 / Zigzag Conversion / 12분

---

leetcode/0chnxxx/Reverse_Integer.kt

- https://leetcode.com/problems/reverse-integer/submissions/1570984169/
- 구현
- 
-

[LTC] Lv2 / Reverse_Integer / 7분

---

leetcode/0chnxxx/String_to_Integer.kt

- https://leetcode.com/problems/string-to-integer-atoi/submissions/1572285992/
- 구현
- 
-

[LTC] Lv2 / String to Integer / 60분

---

leetcode/0chnxxx/Palindrome_Number.kt

- https://leetcode.com/problems/palindrome-number/submissions/1573161079/
- 구현
- 
-

[LTC] Lv1 / Palindrome Number / 23분

---

leetcode/0chnxxx/Container_With_Most_Water.kt

- https://leetcode.com/problems/container-with-most-water/submissions/1574213738/
- 구현
- 
-

[LTC] Lv2 / Container With Most Water / 10분

---

leetcode/0chnxxx/Integer_to_Roman.kt

- https://leetcode.com/problems/integer-to-roman/submissions/1575255315/
- 구현
- 
-

[LTC] Lv2 / Integer to Roman / 26분

---

leetcode/0chnxxx/Roman_to_Integer.kt

- https://leetcode.com/problems/roman-to-integer/submissions/1576320379/
- 구현
- 
-

[LTC] Lv1 / Roman to Integer / 15분

---

leetcode/0chnxxx/Longest_Common_Prefix.kt

- https://leetcode.com/problems/longest-common-prefix/submissions/1577390914/
- 구현
- 
-

[LTC] Lv1 / Longest Common Prefix / 15분

---

leetcode/0chnxxx/3Sum.kt

- https://leetcode.com/problems/3sum/description/
- 구현
- 시간복잡도를 줄일 수 없을 땐 연산 횟수 자체를 줄이는게 최적화에 도움이 된다.
-

[LTC] Lv2 / 3Sum / 30분

---

leetcode/0chnxxx/3Sum_Closest.kt

- https://leetcode.com/problems/3sum-closest/description/
- 구현
- 
-

[LTC] Lv2 / 3Sum Closest / 15분

---

leetcode/0chnxxx/Letter_Combinations_of_a_Phone_Number.kt

- https://leetcode.com/problems/letter-combinations-of-a-phone-number/description/
- 백트래킹(재귀)
- 
-

[LTC] Lv2 / Letter Combinations of a Phone Number / 22분

---

leetcode/0chnxxx/4Sum.kt

- https://leetcode.com/problems/4sum/description/
- 정렬+투 포인터
- 
-

[LTC] Lv2 / 4Sum / 20분

---

leetcode/0chnxxx/Valid_Parentheses.kt

- https://leetcode.com/problems/valid-parentheses/description/
- 스택
- 
-

[LTC] Lv1 / Valid Parentheses / 27분

---

leetcode/0chnxxx/Generate_Parentheses.kt

- https://leetcode.com/problems/generate-parentheses/description/
- 백트래킹
- 
-

[LTC] Lv2 / Generate Parentheses / 8분

---

leetcode/0chnxxx/Swap_Nodes_in_Pairs.kt

- https://leetcode.com/problems/swap-nodes-in-pairs/description/
- 구현
- 
-

[LTC] Lv2 / Swap Nodes in Pairs / 21분

---

leetcode/0chnxxx/Remove_Duplicates_from_Sorted_Array.kt

- https://leetcode.com/problems/remove-duplicates-from-sorted-array/description/
- 구현
- 
-

[LTC] Lv1 / Remove Duplicates from Sorted Array / 12분

---

leetcode/0chnxxx/Remove_Element.kt

- https://leetcode.com/problems/remove-element/description/
- 투포인터
- 
-

[LTC] Lv1 / Remove Element / 30분

---

leetcode/0chnxxx/Find_the_Index_of_the_First_Occurrence_in_a_String.kt

- https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/description/
- KMP 알고리즘
- 
-

[LTC] Lv1 / Find the Index of the First Occurrence in a String / 29분

---

leetcode/0chnxxx/Divide_Two_Integers.kt

- https://leetcode.com/problems/divide-two-integers/description/
- 구현
- 
-

[LTC] Lv2 / Divide Two Integers / 7분

---

leetcode/0chnxxx/Search_in_Rotated_Sorted_Array.kt

- https://leetcode.com/problems/search-in-rotated-sorted-array/description/
- O(N)의 indexOf()를 투 포인터, 이진 탐색으로 최적화
- 
-

[LTC] Lv2 / Search in Rotated Sorted Array / 10분

---

leetcode/0chnxxx/Find_First_and_Last_Position_of_Element_in_Sorted_Array.kt

- https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/
- 이진 탐색
- 
-

[LTC] Lv2 / Find Last Position of Element in Sorted Array / 29분

---

leetcode/0chnxxx/Search_Insert_Position.kt

- https://leetcode.com/problems/search-insert-position/description/
- 이진 탐색
- 
-

[LTC] Lv1 / Search Insert Position / 5분

---

leetcode/0chnxxx/Valid_Sudoku.kt

- https://leetcode.com/problems/valid-sudoku/description/
- 구현
- 
-

[LTC] Lv2 / Valid Sudoku / 55분

---

leetcode/0chnxxx/Count_and_Say.kt

- https://leetcode.com/problems/count-and-say/description/
- 재귀
- 
-

[LTC] Lv2 / Count and Say / 21분

---

leetcode/0chnxxx/Combination_Sum.kt

- https://leetcode.com/problems/combination-sum/description/
- 재귀 백트래킹
- 
-

[LTC] Lv2 / Combination Sum / 22분

---

leetcode/0chnxxx/Combination_Sum_2.kt

- https://leetcode.com/problems/combination-sum-ii/description/
- 조합(DFS + 백트래킹)
- 
-

[LTC] Lv2 / Combination Sum 2 / 13분

---

leetcode/0chnxxx/Multiply_Strings.kt

- https://leetcode.com/problems/multiply-strings/description/
- 구현
- 
-

[LTC] Lv2 / Multiply Strings / 33분

---

leetcode/0chnxxx/Jump_Game_2.kt

- https://leetcode.com/problems/jump-game-ii/description/
- 그리디
- 
-

[LTC] Lv2 / Jump Game 2 / 19분

---

leetcode/0chnxxx/Permutations.kt

- https://leetcode.com/problems/permutations/description/
- 재귀 + 백트래킹
- 
-

[LTC] Lv2 / Permutations / 10분

---

leetcode/0chnxxx/Permutations_2.kt

- https://leetcode.com/problems/permutations-ii/description/
- 재귀 + 백트래킹
- 
-

[LTC ] Lv2 / Permutations 2 / 8분

---

leetcode/0chnxxx/Rotate_Image.kt

- https://leetcode.com/problems/rotate-image/description/
- 구현
- 
-

[LTC] Lv2 / Rotate Image / 17분

---

leetcode/0chnxxx/Group_Anagrams.kt

- https://leetcode.com/problems/group-anagrams/description/
- 구현
- 
-

[LTC] Lv2 / Group Anagrams / 21분

---

leetcode/0chnxxx/Pow(x,n).kt

- https://leetcode.com/problems/powx-n/description/
- 구현
- 
-

[LTC] Lv2 / Pow(x,n) / 40분

---

leetcode/0chnxxx/Spiral_Matrix.kt

- https://leetcode.com/problems/spiral-matrix/description/
- 구현
- List를 사용할 때 고정된 크기라면 ArrayList의 사이즈를 미리 선언해두는게 resize를 최적화 할 수 있다.
-

[LTC] Lv2 / Spiral Matrix / 29분

---

leetcode/0chnxxx/Jump_Game.kt

- https://leetcode.com/problems/jump-game/description/
- 그리디
- 
-

[LTC] Lv2 / Jump Game / 30분

---

leetcode/0chnxxx/Merge_Intervals.kt

- https://leetcode.com/problems/merge-intervals/description/
- 구현
- 
-

[LTC] Lv2 / Merge Intervals / 29분

---

leetcode/0chnxxx/Length_of_Last_Word.kt

- https://leetcode.com/problems/length-of-last-word/description/
- 구현
- 
-

[LTC] Lv1 / Length of Last Word / 6분

---

leetcode/0chnxxx/Sprial_Matrix_2.kt

- https://leetcode.com/problems/spiral-matrix-ii/description/
- 구현
- 
-

[LTC] Lv2 / Sprial Matrix 2 / 12분

---

leetcode/0chnxxx/Rotate_List.kt

- https://leetcode.com/problems/rotate-list/description/
- Linked List / Circular Linked List
- 
-

[LTC] Lv2 / Rotate List / 25분

---

leetcode/0chnxxx/Unique_Paths.kt

- https://leetcode.com/problems/unique-paths/description/
- DP
- 
-

[LTC] Lv2 / Unique Paths / 17분

---

leetcode/0chnxxx/Unique_Paths_2.kt

- https://leetcode.com/problems/unique-paths-ii/description/
- DP
- 이전 문제에서 가지치기 조건을 통해 쉽게 풀 수 있었음
-

[LTC] Lv2 / Unique Paths 2 / 7분

---

leetcode/0chnxxx/Minimum_Path_Sum.kt

- https://leetcode.com/problems/minimum-path-sum/description/
- BFS / DP
- 
-

[LTC] Lv2 / Minimum Path Sum / 30분

---

leetcode/0chnxxx/Plus_One.kt

- https://leetcode.com/problems/plus-one/description/
- 구현
- 
-

[LTC] Lv1 / Plus One / 17분

---

leetcode/0chnxxx/Add_Binary.kt

- https://leetcode.com/problems/add-binary/description/
- 구현
- 
-

[LTC] Lv1 / Add Binary / 20분

---

leetcode/0chnxxx/Edit_Distance.kt

- https://leetcode.com/problems/edit-distance/description
- DP
- 
-

[LTC] Lv2 / Edit Distance / 41분

---

leetcode/0chnxxx/Set_Matrix_Zeroes.kt

- https://leetcode.com/problems/set-matrix-zeroes/description/
- 구현
- 
-

[LTC] Lv2 / Set Matrix Zeroes / 12분

---

leetcode/0chnxxx/Search_a_2D_Matrix.kt

- https://leetcode.com/problems/search-a-2d-matrix/description/
- 이진 탐색
- 
-

[LTC] Lv2 / Search a 2D Matrix / 9분

---

leetcode/0chnxxx/Subsets.kt

- https://leetcode.com/problems/subsets/description/
- DFS + 백트래킹
- 
-

[LTC] Lv2 / Subsets / 17분

---

leetcode/0chnxxx/Word_Search.kt

- https://leetcode.com/problems/word-search/description/
- DFS + 백트래킹
- 
-

[LTC] Lv2 / Word Search / 29분

---

leetcode/0chnxxx/Search_in_Rotated_Sorted_Array_2.kt

- https://leetcode.com/problems/search-in-rotated-sorted-array-ii/description/
- 투포인터
- 
-

[LTC] Lv2 / Search in Rotated Sorted Array 2 / 23분

---

leetcode/0chnxxx/Remove_Duplicates_from_Sorted_List_2.kt

- https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/description/
- 구현
- 
-

[LTC] Lv2 / Remove Duplicates from Sorted List 2 / 33분

---

leetcode/0chnxxx/Partition_List.kt

- https://leetcode.com/problems/partition-list/description/
- 구현
- 
-

[LTC] Lv2 / Partition List / 9분

---

leetcode/0chnxxx/Merge_Sorted_Array.kt

- https://leetcode.com/problems/merge-sorted-array/description/
- 투 포인터
- 
-

[LTC] Lv1 / Merge Sorted Array / 12분

---

leetcode/0chnxxx/Gray_Code.kt

- https://leetcode.com/problems/gray-code/description/
- 비트 연산
- 
-

[LTC] Lv2 / Gray Code / 20분

---

leetcode/0chnxxx/Subsets_2.kt

- https://leetcode.com/problems/subsets-ii/description/
- 백트래킹
- 
-

[LTC] Lv2 / Subsets2 / 8분

---

leetcode/0chnxxx/Decode_Ways.kt

- https://leetcode.com/problems/decode-ways/description/
- DP
- 
-

[LTC] Lv2 / Decode Ways / 17분

---

leetcode/0chnxxx/Reverse_Linked_List_2.kt

- https://leetcode.com/problems/reverse-linked-list-ii/description/
- 구현
- 
-

[LTC] Lv2 / Reverse Linked List 2 / 33분

---

leetcode/0chnxxx/Restore_IP_Addresses.kt

- https://leetcode.com/problems/restore-ip-addresses/description/
- DFS + Backtrack
- 
-

[LTC] Lv2 / Restore IP Addresses / 22분

---

leetcode/0chnxxx/Binary_Tree_Inorder_Traversal.kt

- https://leetcode.com/problems/binary-tree-inorder-traversal/description/
- 구현
-

[LTC] Lv1 / Binary Tree Inorder Traversal / 5분

---

leetcode/0chnxxx/Unique_Binary_Search_Trees.kt

- https://leetcode.com/problems/unique-binary-search-trees/
- 이진 탐색
- 
-

[LTC] Lv2 / Unique Binary Search Trees / 21분

---

leetcode/0chnxxx/Unique_Binary_Search_Trees_2.kt

- https://leetcode.com/problems/unique-binary-search-trees-ii/description/
- 이진 트리
- 
-

[LTC] Lv2 / Unique Binary Search Trees 2 / 23분

---

leetcode/0chnxxx/Interleaving_String.kt

- https://leetcode.com/problems/interleaving-string/description/
- DP
- 
-

[LTC] Lv2 / Interleaving String / 28분

---

leetcode/0chnxxx/Validate_Binary_Search_Tree.kt

- https://leetcode.com/problems/validate-binary-search-tree/description/
- DFS
- 
-

[LTC] Lv2 / Validate Binary Search Tree / 18분

---

leetcode/0chnxxx/Same_Tree.kt

- https://leetcode.com/problems/same-tree/description/
- 이진 트리 + 재귀
- 
-

[LTC] Lv1 / Same Tree / 3분

---

leetcode/0chnxxx/Symmetric_Tree.kt

- https://leetcode.com/problems/symmetric-tree/description/
- 이진 트리 + 재귀
- 
-

[LTC] Lv1 / Symmetric Tree / 5분

---

leetcode/0chnxxx/Binary_Tree_Zigzag_Level_Order_Traversal.kt

- https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/description/
- 이진 트리 + BFS
- 
-

[LTC] Lv2 / Binary Tree Zigzag Level Order Traversal / 12분

---

leetcode/0chnxxx/Maximum_Depth_of_Binary_Tree.kt

- https://leetcode.com/problems/maximum-depth-of-binary-tree/description/
- 이진 트리 + BFS
- 밸런스 트리인 경우 공간복잡도가 최적화될 수 있다.
-

[LTC] Lv1 / Maximum Depth of Binary Tree / 7분

---

leetcode/0chnxxx/Binary_Tree_Level_Order_Traversal_2.kt

- https://leetcode.com/problems/binary-tree-level-order-traversal-ii/description/
- 이진 트리 + BFS
- 
-

[LTC] Lv2 / Binary Tree Level Order Traversal 2 / 4분

---

leetcode/0chnxxx/Convert_Sorted_Array_to_Binary_Search_Tree.kt

- https://leetcode.com/problems/convert-sorted-array-to-binary-search-tree/description/
- BST + 재귀
- 
-

[LTC] Lv1 / Convert Sorted Array to Binary Search Tree / 7분

---

leetcode/0chnxxx/Convert_Sorted_List_to_Binary_Search_Tree.kt

- https://leetcode.com/problems/convert-sorted-list-to-binary-search-tree/description/
- BST + 재귀
- 
-

[LTC] Lv2 / Convert Sorted List to Binary Search Tree / 21분

---

leetcode/0chnxxx/Balanced_Binary_Tree.kt

- https://leetcode.com/problems/balanced-binary-tree/description/
- BST + 재귀
- 
-

[LTC] Lv1 / Balanced Binary Tree / 8분

---

leetcode/0chnxxx/Path_Sum.kt

- https://leetcode.com/problems/path-sum/description/
- 이진 트리 + 재귀
- 
-

[LTC] Lv1 / Path Sum / 13분

---

leetcode/0chnxxx/Pascal's_Triangle.kt

- https://leetcode.com/problems/pascals-triangle/description/
- 구현
- 
-

[LTC] Lv1 / Pascal's Triangle / 7분

---

leetcode/0chnxxx/Pascal's_Triangle_2.kt

- https://leetcode.com/problems/pascals-triangle-ii/description/
- 구현
- 
-

[LTC] Lv1 / Pascal's Triangle 2 / 2분

---

leetcode/0chnxxx/Best_Time_to_Buy_and_Sell_Stock.kt

- https://leetcode.com/problems/best-time-to-buy-and-sell-stock/description/
- 구현
- 
-

[LTC] Lv1 / Best Time to Buy and Sell Stock / 10분

---

leetcode/0chnxxx/Best_Time_to_Buy_and_Sell_Stock_2.kt

- https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/description/
- 구현
- 
-

[LTC] Lv2 / Best Time to Buy and Sell Stock 2 / 7분

---

leetcode/0chnxxx/Valid_Palindrome.kt

- https://leetcode.com/problems/valid-palindrome/description/
- 투 포인터
- 
-

[LTC] Lv1 / Valid Palindrome / 4분

---

leetcode/0chnxxx/Longest_Consecutive_Sequence.kt

- https://leetcode.com/problems/longest-consecutive-sequence/description/
- 구현
- 
-

[LTC] Lv2 / Longest Consecutive Sequence / 4분

---

leetcode/0chnxxx/Sum_Root_to_Leaf_Numbers.kt

- https://leetcode.com/problems/sum-root-to-leaf-numbers/description/
- 이진 트리 + DFS
- 
-

[LTC] Lv2 / Sum Root to Leaf Numbers / 13분

---

leetcode/0chnxxx/Surrounded_Regions.kt

- https://leetcode.com/problems/surrounded-regions/description/
- 2차원 배열 + BFS
- 
-

[LTC] Lv2 / Surrounded Regions / 25분

---

leetcode/0chnxxx/Palindrome_Partitioning.kt

- https://leetcode.com/problems/palindrome-partitioning/description/
- 순열 + 백트래킹 + DP
- 
-

[LTC] Lv2 / Palindrome Partitioning / 7분

---

leetcode/0chnxxx/Clone_Graph.kt

- https://leetcode.com/problems/clone-graph/description/
- 그래프 + DFS
- 
-

[LTC] Lv2 / Clone Graph / 8분

---

leetcode/0chnxxx/Gas_Station.kt

- https://leetcode.com/problems/gas-station/description/
- 그리디
- 
-

[LTC] Lv2 / Gas Station / 7분

---

leetcode/0chnxxx/Single_Number.kt

- https://leetcode.com/problems/single-number/description/
- 구현
- 
-

[LTC] Lv1 / Single Number / 4분

---

leetcode/0chnxxx/Copy_List_with_Random_Pointer.kt

- https://leetcode.com/problems/copy-list-with-random-pointer/description/
- 연결 리스트
- 
-

[LTC] Lv2 / Copy List with Random Pointer / 13분

---

leetcode/0chnxxx/Word_Break.kt

- https://leetcode.com/problems/word-break/description/
- DP
- 
-

[LTC] Lv2 / Word Break / 9분

---

leetcode/0chnxxx/Linked_List_Cycle.kt

- https://leetcode.com/problems/linked-list-cycle/description/
- 연결 리스트
- 
-

[LTC] Lv1 / Linked List Cycle / 5분

---

leetcode/0chnxxx/Reorder_List.kt

- https://leetcode.com/problems/reorder-list/description/
- 연결 리스트
- 
-

[LTC] Lv2 / Reorder List / 10분

---

leetcode/0chnxxx/Binary_Tree_Preorder_Traversal.kt

- https://leetcode.com/problems/binary-tree-preorder-traversal/description/
- 이진 트리
- 
-

[LTC] Lv1 / Binary Tree Preorder Traversal / 1분

---

leetcode/0chnxxx/Binary_Tree_Postorder_Traversal.kt

- https://leetcode.com/problems/binary-tree-postorder-traversal/description/
- 이진 트리
- 
-

[LTC] Lv1 / Binary Tree Postorder Traversal / 2분

---

leetcode/0chnxxx/Maximum_Product_Subarray.kt

- https://leetcode.com/problems/maximum-product-subarray/description/
- 구현
- 
-

[LTC] Lv2 / Maximum Product Subarray / 10분

---

leetcode/0chnxxx/Find_Minimum_in_Rotated_Sorted_Array.kt

- https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/
- 이진 탐색
- 
-

[LTC] Lv2 / Find Minimum in Rotated Sorted Array / 11분

---

leetcode/0chnxxx/Min_Stack.kt

- https://leetcode.com/problems/min-stack/description/
- 구현
- 
-

[LTC] Lv2 / Min Stack / 4분

---

leetcode/0chnxxx/Find_Peak_Element.kt

- https://leetcode.com/problems/find-peak-element/description/
- 이진 탐색
- 
-

[LTC] Lv2 / Find Peak Element / 8분

---

leetcode/0chnxxx/Maximum_Gap.kt

- https://leetcode.com/problems/maximum-gap/description/
- 구현
- 
-

[LTC] Lv2 / Maximum Gap / 5분

---

leetcode/0chnxxx/Compare_Version_Numbers.kt

- https://leetcode.com/problems/compare-version-numbers/description/
- 구현
- 
-

[LTC] Lv2 / Compare Version Numbers / 7분

---

leetcode/0chnxxx/Fraction_to_Recurring_Decimal.kt

- https://leetcode.com/problems/fraction-to-recurring-decimal/description/
- 구현
- 
-

[LTC] Lv2 / Fraction to Recurring Decimal / 15분

---

leetcode/0chnxxx/Excel_Sheet_Column_Title.kt

- https://leetcode.com/problems/excel-sheet-column-title/description/
- 구현
- 
-

[LTC] Lv1 / Excel Sheet Column Title / 6분

---

leetcode/0chnxxx/Excel_Sheet_Column_Number.kt

- https://leetcode.com/problems/excel-sheet-column-number/description/
- 구현
- 
-

[LTC] Lv1 / Excel Sheet Column Number / 8분

---

leetcode/0chnxxx/Factorial_Trailing_Zeroes.kt

- https://leetcode.com/problems/factorial-trailing-zeroes/description/
- 구현
- 
-

[LTC] Lv2 / Factorial Trailing Zeroes / 6분

---

leetcode/0chnxxx/Largest_Number.kt

- https://leetcode.com/problems/largest-number/description/
- 정렬
- 
-

[LTC] Lv2 / Largest Number / 11분

---

leetcode/0chnxxx/Repeated_DNA_Sequences.kt

- https://leetcode.com/problems/repeated-dna-sequences/description/
- 구현
- 
-

[LTC] Lv2 / Repeated DNA Sequences / 4분

---

leetcode/0chnxxx/Rotate_Array.kt

- https://leetcode.com/problems/rotate-array/description/
- 구현
- 
-

[LTC] Lv2 / Rotate Array / 6분

---

leetcode/0chnxxx/Reverse_Bits.kt

- https://leetcode.com/problems/reverse-bits/description/
- 비트연산
- 
-

[LTC] Lv1 / Reverse Bits / 9분

---

leetcode/0chnxxx/Number_of_1_Bits.kt

- https://leetcode.com/problems/number-of-1-bits/description/
- 비트 연산
- 
-

[LTC] Lv1 / Number of 1 Bits / 1분

---

leetcode/0chnxxx/House_Robber.kt

- https://leetcode.com/problems/house-robber/description/
- DP
- 
-

[LTC] Lv2 / House Robber / 7분

---

leetcode/0chnxxx/Number_of_Islands.kt

- https://leetcode.com/problems/number-of-islands/
- BFS
- 
-

[LTC] Lv2 / Number of Islands / 7분

---

leetcode/0chnxxx/Bitwise_AND_of_Numbers_Range.kt

- https://leetcode.com/problems/bitwise-and-of-numbers-range/description/
- 비트 연산
- 
-

[LTC] Lv2 / Bitwise AND of Numbers Range / 2분

---

leetcode/0chnxxx/Happy_Number.kt

- https://leetcode.com/problems/happy-number/description/
- 구현
- 
-

[LTC] Lv1 / Happy Number / 4분

---

leetcode/0chnxxx/Remove_Linked_List_Elements.kt

- https://leetcode.com/problems/remove-linked-list-elements/description/
- 연결 리스트
- 
-

[LTC] Lv1 / Remove Linked List Elements / 10분

---

leetcode/0chnxxx/Count_Primes.kt

- https://leetcode.com/problems/count-primes/description/
- 구현
- 
-

[LTC] Lv2 / Count Primes / 6분

---

leetcode/0chnxxx/Isomorphic_Strings.kt

- https://leetcode.com/problems/isomorphic-strings/description/
- 구현
- 
-

[LTC] Lv1 / Isomorphic Strings / 6분

---

leetcode/0chnxxx/Reverse_Linked_List.kt

- https://leetcode.com/problems/reverse-linked-list/description/
- 연결 리스트
- 
-

[LTC] Lv1 / Reverse Linked List / 7분

---

leetcode/0chnxxx/Implement_Trie_(Prefix_Tree).kt

- https://leetcode.com/problems/implement-trie-prefix-tree/description/
- 트라이 노드 구현
- 
-

[LTC] Lv2 / Implement Trie (Prefix Tree) / 6분

---

leetcode/0chnxxx/Minimum_Size_Subarray_Sum.kt

- https://leetcode.com/problems/minimum-size-subarray-sum/description/
- 슬라이딩 윈도우
- 
-

[LTC] Lv2 / Minimum Size Subarray Sum / 3분

---

leetcode/0chnxxx/Course_Schedule_2.kt

- https://leetcode.com/problems/course-schedule-ii/description/
- 그래프
- 
-

[LTC] Lv2 / Course Schedule 2 / 13분

---

leetcode/0chnxxx/Design_Add_and_Search_Words_Data_Structure.kt

- https://leetcode.com/problems/design-add-and-search-words-data-structure/description/
- 구현
- 
-

[LTC] Lv2 / Design Add and Search Words Data Structure / 13분

---

leetcode/0chnxxx/House_Robber_2.kt

- https://leetcode.com/problems/house-robber-ii/description/
- DP
- 
-

[LTC] Lv2 / House Robber 2 / 8분

---

leetcode/0chnxxx/Kth_Largest_Element_in_an_Array.kt

- https://leetcode.com/problems/kth-largest-element-in-an-array/description/
- Counting Sort
- 
-

[LTC] Lv2 / Kth Largest Element in an Array / 14분

---

leetcode/0chnxxx/Invert_Binary_Tree.kt

- https://leetcode.com/problems/invert-binary-tree/description/
- 재귀
- 
-

[LTC] Lv1 / Invert Binary Tree / 4분

---

leetcode/0chnxxx/Basic_Calculator_2.kt

- https://leetcode.com/problems/basic-calculator-ii/description/
- 구현
- 
-

[LTC] Lv2 / Basic Calculator 2 / 6분

---

leetcode/0chnxxx/Summary_Ranges.kt

- https://leetcode.com/problems/summary-ranges/description/
- 구현
- 
-

[LTC] Lv1 / Summary Ranges / 17분

---

leetcode/0chnxxx/Kth_Smallest_Element_in_a_BST.kt

- https://leetcode.com/problems/kth-smallest-element-in-a-bst/description/
- BST + 중위순회 + 재귀
- 
-

[LTC] Lv2 / Kth Smallest Element in a BST / 6분

---

leetcode/0chnxxx/Palindrome_Linked_List.kt

- https://leetcode.com/problems/palindrome-linked-list/description/
- 연결 리스트
- 
-

[LTC] Lv1 / Palindrome Linked List / 7분

---

leetcode/0chnxxx/Lowest_Common_Ancestor_of_a_Binary_Search_Tree.kt

- https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description/
- BST
- 
-

[LTC] Lv2 / Lowest Common Ancestor of a Binary Search Tree / 5분

---

leetcode/0chnxxx/Lowest_Common_Ancestor_of_a_Binary_Tree.kt

- https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/
- 이진 트리
- 
-

[LTC] Lv2 / Lowest Common Ancestor of a Binary Tree / 5분

---

leetcode/0chnxxx/Delete_Node_in_a_Linked_List.kt

- https://leetcode.com/problems/delete-node-in-a-linked-list/description/
- 연결 리스트
- 
-

[LTC] Lv2 / Delete Node in a Linked List / 8분

---

leetcode/0chnxxx/Search_a_2D_Matrix_2.kt

- https://leetcode.com/problems/search-a-2d-matrix-ii/description/
- 2차원 배열
- 
-

[LTC] Lv2 / Search a 2D Matrix 2 / 5분

---

leetcode/0chnxxx/Different_Ways_to_Add_Parentheses.kt

- https://leetcode.com/problems/different-ways-to-add-parentheses/description/
- 구현
- 
-

[LTC] Lv2 / Different Ways to Add Parentheses / 6분

---

leetcode/0chnxxx/Binary_Tree_Paths.kt

- https://leetcode.com/problems/binary-tree-paths/description/
- 트리
- 
-

[LTC] Lv1 / Binary Tree Paths / 10분

---

leetcode/0chnxxx/Add_Digits.kt

- https://leetcode.com/problems/add-digits/description/
- 구현
- 
-

[LTC] Lv1 / Add Digits / 7분

---

leetcode/0chnxxx/Single_Number_3.kt

- https://leetcode.com/problems/single-number-iii/description/
- 비트 연산
- 
-

[LTC] Lv2 / Single Number 3 / 10분

---

leetcode/0chnxxx/Ugly_Number.kt

- https://leetcode.com/problems/ugly-number/description/
- 소인수
- 
-

[LTC] Lv1 / Ugly Number / 4분

---

leetcode/0chnxxx/Ugly_Number_2.kt

- https://leetcode.com/problems/ugly-number-ii/description/
- DP
- 
-

[LTC] Lv2 / Ugly Number 2 / 7분

---

leetcode/0chnxxx/H-Index_2.kt

- https://leetcode.com/problems/h-index-ii/description/
- 이진 탐색
- 
-

[LTC] Lv2 / H-Index 2 / 11분

---

leetcode/0chnxxx/First_Bad_Version.kt

- https://leetcode.com/problems/first-bad-version/description/
- 이진 탐색
- 
-

[LTC] Lv1 / First Bad Version / 10분

---

leetcode/0chnxxx/Move_Zeroes.kt

- https://leetcode.com/problems/move-zeroes/description/
- 구현
- 
-

[LTC] Lv1 / Move Zeores / 3분

---

leetcode/0chnxxx/Peeking_Iterator.kt

- https://leetcode.com/problems/peeking-iterator/description/
- 구현
- 
-

[LTC] Lv2 / Peeking Iterator / 10분

---

leetcode/0chnxxx/Find_the_Duplicate_Number.kt

- https://leetcode.com/problems/find-the-duplicate-number/description/
- 사이클 탐색
- 
-

[LTC] Lv2 / Find the Duplicate Number / 7분

---

leetcode/0chnxxx/Word_Pattern.kt

- https://leetcode.com/problems/word-pattern/description/
- 구현
- 
-

[LTC] Lv1 / Word Pattern / 15분

---

leetcode/0chnxxx/Nim_Game.kt

- https://leetcode.com/problems/nim-game/description/
- 수학
- 
-

[LTC] Lv1 / Nim Game / 4분

---

leetcode/0chnxxx/Longest_Increasing_Subsequence.kt

- https://leetcode.com/problems/longest-increasing-subsequence/description/
- 이진 탐색
- 
-

[LTC] Lv2 / Longest Increasing Subsequence / 4분

---

leetcode/0chnxxx/Range_Sum_Query_Immutable.kt

- https://leetcode.com/problems/range-sum-query-immutable/description/
- 누적합
- 
-

[LTC] Lv1 / Range Sum Query - Immutable / 6분

---

leetcode/0chnxxx/Range_Sum_Query_2D_Immutable.kt

- https://leetcode.com/problems/range-sum-query-2d-immutable/description/
- 누적합
- 
-

[LTC] Lv2 / Range Sum Query 2D - Immutable / 5분

---

leetcode/0chnxxx/Additive_Number.kt

- https://leetcode.com/problems/additive-number/description/
- 구현
- 
-

[LTC] Lv2 / Additive Number / 6분

---

leetcode/0chnxxx/Best_Time_to_Buy_and_Sell_Stock_with_Cooldown.kt

- https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/
- 상태 전이 DP
- 
-

[LTC] Lv2 / Best Time to Buy and Sell Stock with Cooldown / 5분

---

leetcode/0chnxxx/Minimum_Height_Trees.kt

- https://leetcode.com/problems/minimum-height-trees/description/
- 그래프 & BFS
- 
-

[LTC] Lv2 / Minimum Height Trees / 18분

---

leetcode/0chnxxx/Remove_Duplicate_Letters.kt

- https://leetcode.com/problems/remove-duplicate-letters/description/
- 스택
- 
-

[LTC] Lv2 / Remove Duplicate Letters / 12분

---

leetcode/0chnxxx/Wiggle_Sort_2.kt

- https://leetcode.com/problems/wiggle-sort-ii/description/
- 구현
- 
-

[LTC] Lv2 / Wiggle Sort 2 / 5분

---

leetcode/0chnxxx/Power_of_Three.kt

- https://leetcode.com/problems/power-of-three/description/
- 구현
- 
-

[LTC] Lv1 / Power of Three / 6분

---

leetcode/0chnxxx/Verify_Preorder_Serialization_of_a_Binary_Tree.kt

- https://leetcode.com/problems/verify-preorder-serialization-of-a-binary-tree/description/
- 구현
- 
-

[LTC] Lv2 / Verify Preorder Serialization of a Binary Tree / 6분

---

leetcode/0chnxxx/Increasing_Triplet_Subsequence.kt

- https://leetcode.com/problems/increasing-triplet-subsequence/description/
- 구현
- 
-

[LTC] Lv2 / Increasing Triplet Subsequence / 7분
